name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11 and maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        maven: '3.1.0'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Execute jar file
      run: |
          PID=$(sudo lsof -t -i:8080)
          if [ -n "$PID" ]; then
            echo "Killing existing process with PID $PID"
            sudo kill -9 $PID
          else
            echo "No existing process found on port 8080"
          fi
          sudo java -jar /home/ec2-user/_work/hackathon-backend/hackathon-backend/target/hackathon-backend-0.0.1-SNAPSHOT.jar &
